import { User, Announcement, Event, Club } from '../types';

// Mock Users
export const mockUsers: User[] = [
  {
    id: '1',
    name: 'John Doe',
    email: 'john.doe@campus.edu',
    role: 'student',
    department: 'Computer Science',
    year: 3,
  },
  {
    id: '2',
    name: 'Jane Smith',
    email: 'jane.smith@campus.edu',
    role: 'faculty',
    department: 'Computer Science',
  },
  {
    id: '3',
    name: 'Alice Johnson',
    email: 'alice.j@campus.edu',
    role: 'student',
    department: 'Electrical Engineering',
    year: 2,
  },
  {
    id: '4',
    name: 'Bob Wilson',
    email: 'bob.w@campus.edu',
    role: 'student',
    department: 'Computer Science',
    year: 4,
  },
];

// Mock Announcements
export const mockAnnouncements: Announcement[] = [
  {
    id: '1',
    title: 'Mid-Semester Examination Schedule Released',
    content: 'The mid-semester examination schedule for all departments has been released. Please check the academic portal for your specific exam dates and times. Make sure to carry your student ID card to the examination hall.',
    author: mockUsers[1],
    category: 'academic',
    createdAt: '2025-11-10T10:00:00Z',
    isPinned: true,
    tags: ['exams', 'important', 'academic'],
  },
  {
    id: '2',
    title: 'Campus Tech Fest 2025 - Call for Participants',
    content: 'Get ready for the biggest technical fest of the year! Register your teams for hackathons, coding competitions, and tech talks. Early bird registration closes on Nov 20th.',
    author: mockUsers[0],
    category: 'event',
    createdAt: '2025-11-09T14:30:00Z',
    isPinned: true,
    tags: ['techfest', 'competition', 'registration'],
  },
  {
    id: '3',
    title: 'Library Hours Extended for Exam Week',
    content: 'The central library will remain open 24/7 during the exam week (Nov 18-25). Additional study rooms have been allocated in the academic block.',
    author: mockUsers[1],
    category: 'administrative',
    createdAt: '2025-11-08T09:00:00Z',
    isPinned: false,
    tags: ['library', 'facilities', 'exams'],
  },
  {
    id: '4',
    title: 'Coding Club Workshop: Introduction to React',
    content: 'Join us this Saturday for a hands-on workshop on React.js. Perfect for beginners! Venue: Lab 3, Time: 2 PM - 5 PM. Limited seats available.',
    author: mockUsers[3],
    category: 'club',
    createdAt: '2025-11-07T16:00:00Z',
    isPinned: false,
    tags: ['workshop', 'coding', 'react'],
  },
  {
    id: '5',
    title: 'Campus Placement Drive - Multiple Companies',
    content: 'Major tech companies including Google, Microsoft, and Amazon will be visiting campus for placement drives next month. Ensure your resume is updated on the placement portal.',
    author: mockUsers[1],
    category: 'academic',
    createdAt: '2025-11-06T11:00:00Z',
    isPinned: false,
    tags: ['placements', 'career', 'opportunities'],
  },
];

// Mock Events
export const mockEvents: Event[] = [
  {
    id: '1',
    title: 'Annual Tech Symposium 2025',
    description: 'A two-day technical symposium featuring keynote speeches from industry leaders, technical workshops, and networking opportunities.',
    organizer: mockUsers[1],
    startDate: '2025-11-20T09:00:00Z',
    endDate: '2025-11-21T18:00:00Z',
    location: 'Main Auditorium',
    category: 'technical',
    maxAttendees: 500,
    attendees: [mockUsers[0], mockUsers[2]],
    tags: ['symposium', 'technical', 'networking'],
  },
  {
    id: '2',
    title: 'Hackathon: Code for Change',
    description: '24-hour hackathon focused on building solutions for social good. Form teams of 2-4 members and compete for exciting prizes!',
    organizer: mockUsers[0],
    startDate: '2025-11-25T10:00:00Z',
    endDate: '2025-11-26T10:00:00Z',
    location: 'Computer Science Block',
    category: 'technical',
    maxAttendees: 100,
    attendees: [mockUsers[2], mockUsers[3]],
    tags: ['hackathon', 'coding', 'competition'],
  },
  {
    id: '3',
    title: 'Cultural Night - Festival of Lights',
    description: 'Celebrate the festival of lights with cultural performances, music, dance, and traditional cuisine from around the world.',
    organizer: mockUsers[3],
    startDate: '2025-11-15T18:00:00Z',
    endDate: '2025-11-15T22:00:00Z',
    location: 'Open Air Theatre',
    category: 'cultural',
    attendees: [mockUsers[0], mockUsers[1], mockUsers[2]],
    tags: ['cultural', 'festival', 'performance'],
  },
  {
    id: '4',
    title: 'Inter-College Basketball Tournament',
    description: 'Annual basketball tournament featuring teams from colleges across the region. Come cheer for our home team!',
    organizer: mockUsers[2],
    startDate: '2025-11-18T14:00:00Z',
    endDate: '2025-11-19T20:00:00Z',
    location: 'Sports Complex',
    category: 'sports',
    maxAttendees: 1000,
    attendees: [mockUsers[0], mockUsers[3]],
    tags: ['sports', 'basketball', 'tournament'],
  },
  {
    id: '5',
    title: 'Guest Lecture: AI and the Future',
    description: 'Distinguished professor from MIT will discuss the future of artificial intelligence and its impact on society.',
    organizer: mockUsers[1],
    startDate: '2025-11-22T15:00:00Z',
    endDate: '2025-11-22T17:00:00Z',
    location: 'Lecture Hall 1',
    category: 'academic',
    maxAttendees: 200,
    attendees: [mockUsers[0]],
    tags: ['lecture', 'AI', 'technology'],
  },
];

// Mock Clubs
export const mockClubs: Club[] = [
  {
    id: '1',
    name: 'Coding Club',
    description: 'A community of passionate coders who love to build, learn, and share knowledge. We organize weekly coding sessions, hackathons, and workshops on various technologies.',
    category: 'technical',
    members: [mockUsers[0], mockUsers[2], mockUsers[3]],
    admins: [mockUsers[0]],
    foundedDate: '2020-08-15',
    contactEmail: 'codingclub@campus.edu',
    socialLinks: {
      website: 'https://codingclub.campus.edu',
      instagram: '@campuscodingclub',
    },
  },
  {
    id: '2',
    name: 'Robotics Society',
    description: 'Building autonomous robots and competing in national and international robotics competitions. Join us to explore the world of robotics and automation.',
    category: 'technical',
    members: [mockUsers[1], mockUsers[2]],
    admins: [mockUsers[2]],
    foundedDate: '2019-01-10',
    contactEmail: 'robotics@campus.edu',
    socialLinks: {
      website: 'https://robotics.campus.edu',
      twitter: '@campusrobotics',
    },
  },
  {
    id: '3',
    name: 'Drama Club',
    description: 'Bringing stories to life through theater and performance. We perform multiple plays throughout the year and welcome actors, directors, and crew members.',
    category: 'cultural',
    members: [mockUsers[0], mockUsers[3]],
    admins: [mockUsers[3]],
    foundedDate: '2018-09-01',
    contactEmail: 'drama@campus.edu',
    socialLinks: {
      instagram: '@campusdrama',
    },
  },
  {
    id: '4',
    name: 'Photography Club',
    description: 'Capturing moments and telling stories through the lens. We organize photo walks, exhibitions, and workshops on photography techniques.',
    category: 'cultural',
    members: [mockUsers[1], mockUsers[2], mockUsers[3]],
    admins: [mockUsers[1]],
    foundedDate: '2020-02-14',
    contactEmail: 'photography@campus.edu',
    socialLinks: {
      instagram: '@campusphoto',
      website: 'https://photography.campus.edu',
    },
  },
  {
    id: '5',
    name: 'Cricket Club',
    description: 'For cricket enthusiasts! Regular practice sessions, inter-department tournaments, and representing the college at regional competitions.',
    category: 'sports',
    members: [mockUsers[0], mockUsers[2]],
    admins: [mockUsers[2]],
    foundedDate: '2017-03-20',
    contactEmail: 'cricket@campus.edu',
    socialLinks: {},
  },
  {
    id: '6',
    name: 'Entrepreneurship Cell',
    description: 'Fostering entrepreneurial spirit among students. We organize startup pitch competitions, mentorship programs, and networking events with successful entrepreneurs.',
    category: 'academic',
    members: [mockUsers[0], mockUsers[1], mockUsers[3]],
    admins: [mockUsers[0], mockUsers[1]],
    foundedDate: '2019-07-01',
    contactEmail: 'ecell@campus.edu',
    socialLinks: {
      website: 'https://ecell.campus.edu',
      linkedin: 'campus-ecell',
      twitter: '@campusecell',
    },
  },
];
