import fs from 'fs';
import path from 'path';

import { connectDatabase } from '../src/config/database.js';
import { env } from '../src/config/env.js';
import { User } from '../src/models/User.js';
import { Club } from '../src/models/Club.js';
import { Event } from '../src/models/Event.js';
import { Announcement } from '../src/models/Announcement.js';
import { Notification } from '../src/models/Notification.js';
import { Feedback } from '../src/models/Feedback.js';
import { Certificate } from '../src/models/Certificate.js';
import { ActivityLog } from '../src/models/ActivityLog.js';

const sampleCertificateName = 'sample-certificate.pdf';

const ensureSampleCertificate = () => {
  if (!fs.existsSync(env.certificateBasePath)) {
    fs.mkdirSync(env.certificateBasePath, { recursive: true });
  }
  const samplePath = path.join(env.certificateBasePath, sampleCertificateName);
  if (!fs.existsSync(samplePath)) {
    fs.writeFileSync(
      samplePath,
      'Sample certificate placeholder generated by seed script. Replace with a real PDF if needed.'
    );
  }
  return sampleCertificateName;
};

const clearCollections = async () => {
  await Promise.all([
    Announcement.deleteMany({}),
    Certificate.deleteMany({}),
    Club.deleteMany({}),
    Event.deleteMany({}),
    Feedback.deleteMany({}),
    Notification.deleteMany({}),
    User.deleteMany({}),
    ActivityLog.deleteMany({}),
  ]);
};

const seedUsers = async () => {
  const [admin, clubAdminA, clubAdminB, studentA, studentB, faculty] = await User.create([
    {
      name: 'Zaeem Ul Hassan',
      email: 'zaeem@lgu.edu',
      password: 'supersecret',
      role: 'admin',
      department: 'Campus Strategy',
      bio: 'Platform coordinator ensuring everything runs smoothly.',
      interests: ['Leadership', 'Innovation'],
    },
    {
      name: 'Ahsan Malik',
      email: 'ahsan@lgu.edu',
      password: 'supersecret',
      role: 'club_admin',
      department: 'Engineering',
      bio: 'Leads the Robotics & AI Society.',
      interests: ['Robotics', 'DIY'],
    },
    {
      name: 'Bakhtawar Khan',
      email: 'bakhtawar@lgu.edu',
      password: 'supersecret',
      role: 'club_admin',
      department: 'Design & Arts',
      bio: 'Heads the Creative Studio for all design projects.',
    },
    {
      name: 'Saad Qureshi',
      email: 'saad@lgu.edu',
      password: 'supersecret',
      role: 'student',
      year: 3,
      department: 'Computer Science',
      interests: ['AI', 'Hackathons'],
    },
    {
      name: 'Nimra Yousaf',
      email: 'nimra@lgu.edu',
      password: 'supersecret',
      role: 'student',
      year: 2,
      department: 'Business Administration',
      interests: ['Marketing', 'Community Building'],
    },
    {
      name: 'Prof. Farooq Ahmed',
      email: 'farooq.ahmed@lgu.edu',
      password: 'supersecret',
      role: 'faculty',
      department: 'Humanities',
    },
  ]);

  return { admin, clubAdminA, clubAdminB, studentA, studentB, faculty };
};

const seedClubs = async ({ admin, clubAdminA, clubAdminB, studentA, studentB }) => {
  const clubs = await Club.create([
    {
      name: 'LGU Robotics & AI Society',
      description: 'Weekly meetups exploring intelligent systems, drones, and computer vision.',
      category: 'technical',
      contactEmail: 'roboticsai@lgu.edu',
      admins: [clubAdminA._id],
      members: [clubAdminA._id, studentA._id, studentB._id],
      createdBy: admin._id,
    },
    {
      name: 'Lahore Creative Studio',
      description: 'Design jams, typography labs, and portfolio reviews for budding artists.',
      category: 'cultural',
      contactEmail: 'creative@lgu.edu',
      admins: [clubAdminB._id],
      members: [clubAdminB._id, studentB._id],
      createdBy: admin._id,
    },
  ]);

  // backfill club reference on club admins
  await Promise.all(
    clubs.map((club, index) => {
      const adminUser = index === 0 ? clubAdminA : clubAdminB;
      return User.findByIdAndUpdate(adminUser._id, { club: club._id });
    })
  );

  return clubs;
};

const seedAnnouncements = async ({ admin, faculty }) => {
  return Announcement.create([
    {
      title: 'LGU CampusConnect Live',
      content: 'Explore the refreshed platform for events, clubs, and certificates tailored for LGU.',
      category: 'general',
      author: admin._id,
      isPinned: true,
      tags: ['launch', 'lgu'],
    },
    {
      title: 'Humanities Dialogue Series',
      content: 'Prof. Farooq invites you to a week-long conversation on culture and art in Pakistan.',
      category: 'academic',
      author: faculty._id,
      tags: ['humanities', 'dialogue'],
    },
  ]);
};

const seedEvents = async ({ clubAdminA, clubAdminB, studentA, studentB }, clubs) => {
  const [aiSociety, creativeCollective] = clubs;

  const hackathon = await Event.create({
    title: 'LGU Innovators Sprint',
    description: '48-hour prototype sprint with mentors from Pakistani tech startups.',
    organizer: clubAdminA._id,
    club: aiSociety._id,
    startDate: new Date(Date.now() + 7 * 24 * 60 * 60 * 1000),
    endDate: new Date(Date.now() + 8 * 24 * 60 * 60 * 1000),
    registrationDeadline: new Date(Date.now() + 5 * 24 * 60 * 60 * 1000),
    location: 'LGU Innovation Lab',
    category: 'technical',
    maxAttendees: 200,
    tags: ['hackathon', 'ai'],
  });

  const designShowcase = await Event.create({
    title: 'Lahore Design Showcase',
    description: 'Students display their UX/UI work inspired by Pakistani art and culture.',
    organizer: clubAdminB._id,
    club: creativeCollective._id,
    startDate: new Date(Date.now() - 14 * 24 * 60 * 60 * 1000),
    endDate: new Date(Date.now() - 13 * 24 * 60 * 60 * 1000),
    registrationDeadline: new Date(Date.now() - 16 * 24 * 60 * 60 * 1000),
    location: 'LGU Art Gallery',
    category: 'cultural',
    status: 'completed',
    tags: ['design', 'showcase'],
    attendees: [studentA._id, studentB._id],
  });

  return { hackathon, designShowcase };
};

const seedNotifications = async ({ admin, clubAdminA }, clubs) => {
  const [aiSociety] = clubs;
  return Notification.create([
    {
      title: 'Hackathon Registration Closing',
      message: 'Spots are almost full—submit your team today.',
      link: 'https://campusconnect.dev/events/hackathon',
      targetRoles: ['student'],
      club: aiSociety._id,
      createdBy: clubAdminA._id,
    },
    {
      title: 'Platform Tips',
      message: 'Remember to upload your club banners for better visibility.',
      targetRoles: [],
      createdBy: admin._id,
    },
  ]);
};

const seedFeedbackAndCertificates = async ({ studentA, studentB }, events) => {
  const { designShowcase } = events;

  await Feedback.create([
    {
      event: designShowcase._id,
      user: studentA._id,
      rating: 5,
      comment: 'Inspiring projects and great networking!',
    },
    {
      event: designShowcase._id,
      user: studentB._id,
      rating: 4,
      comment: 'Loved the creativity—would enjoy more critique sessions.',
    },
  ]);

  const fileName = ensureSampleCertificate();
  await Certificate.create({
    event: designShowcase._id,
    user: studentA._id,
    fileName,
  });
};

const logSeedActivity = async ({ admin }) => {
  await ActivityLog.create({
    user: admin._id,
    action: 'seed.run',
    entity: 'SeedScript',
    metadata: { message: 'Database seeded with sample CampusConnect data.' },
  });
};

const run = async () => {
  try {
    console.log('Connecting to MongoDB...');
    await connectDatabase();
    console.log('Clearing existing data...');
    await clearCollections();

    console.log('Seeding users...');
    const users = await seedUsers();
    console.log('Seeding clubs...');
    const clubs = await seedClubs(users);
    console.log('Seeding announcements...');
    await seedAnnouncements(users);
    console.log('Seeding events...');
    const events = await seedEvents(users, clubs);
    console.log('Seeding notifications...');
    await seedNotifications(users, clubs);
    console.log('Seeding feedback + certificates...');
    await seedFeedbackAndCertificates(users, events);
    console.log('Recording seed activity...');
    await logSeedActivity(users);

    console.log('✅ Seed completed successfully');
    process.exit(0);
  } catch (error) {
    console.error('❌ Seed failed:', error);
    process.exit(1);
  }
};

run();
